version: '3.4'
services:
  zookeeper:
    build: ./zookeeper
    image: onprem/zookeeper:5.3.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - $PWD/security:/security
    environment:
      KAFKA_OPTS: -Djava.security.auth.login.config=/security/zookeeper_jaas.conf
         -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
         -Dzookeeper.requireClientAuthScheme=sasl
      
  kafka:
    build: ./kafka
    image: onprem/kafka:5.3.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    volumes:
      - $PWD/security:/security
    ports:
      - "9092:9092"
    environment:
      KAFKA_OPTS: "-Djava.security.auth.login.config=/security/broker_jaas.conf"
  
  ksql-server:
    build: ./ksql-server
    image: onprem/ksql-server:5.3.0
    hostname: ksql-server
    container_name: ksql-server
    depends_on:
      - kafka
    ports:
      - "8088:8088"
    volumes:
      - $PWD/security:/security
    environment:
      KSQL_OPTS: "-Dava.security.auth.login.config=/security/ksql_jaas.conf"
