---
version: '3.4'
services:
  ksql-server:
    image: confluentinc/cp-ksql-server:$TAG
    hostname: ksql-server
    container_name: ksql-server
    ports:
      - "8088:8088"
    environment:
      #      KSQL_CONFIG_DIR: "/etc/ksql"
      #KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties"
      KSQL_BOOTSTRAP_SERVERS: "pkc-l7koe.eu-west-1.aws.confluent.cloud:9092"
      KSQL_INTERNAL_TOPIC_REPLICAS: 3
      KSQL_STREAMS_REPLICATION_FACTOR: 3
      KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR: 3
      KSQL_SECURITY_PROTOCOL: SASL_SSL
      KSQL_SASL_MECHANISM: PLAIN
      KSQL_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required \
              username="$api-key" \
              password="api-key-secret";
      KSQL_HOST_NAME: ksql-server
      KSQL_SERVICE_ID: "myksql-"
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0

