version: '2.3'
services:
  zookeeper-src:
    image: confluentinc/cp-zookeeper:$TAG
    hostname: zookeeper-src
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-src:2888:3888

  zookeeper-dest:
    image: confluentinc/cp-zookeeper:$TAG
    hostname: zookeeper-dest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-dest:2888:3888

  kafka-src:
    image: confluentinc/cp-enterprise-kafka:$TAG
    hostname: kafka-src
    depends_on:
      - zookeeper-src
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-src:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-src:9092

  kafka-dest:
    image: confluentinc/cp-enterprise-kafka:$TAG
    hostname: kafka-dest
    depends_on:
      - zookeeper-dest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-dest:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-dest:9092

  connect:
    image: confluentinc/cp-enterprise-replicator:$TAG
    hostname: connect
    restart: on-failure:3
    ports:
      - "8082:8082"
    depends_on:
      - zookeeper-dest
      - kafka-dest
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka-dest:9092"
      CONNECT_GROUP_ID: "connect"
      CONNECT_REST_PORT: 8082
      CONNECT_CONFIG_STORAGE_TOPIC: connect-config
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
      CONNECT_PLUGIN_PATH: "/usr/share/java"
      CONNECT_LOG4J_ROOT_LOGLEVEL: DEBUG
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
    volumes:
      - /tmp/replicator-host-cluster-test/:/tmp/test

