---
version: '3'
services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:$TAG
    hostname: zookeeper1
    restart: on-failure:3
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: DEBUG
      ZOOKEEPER_TICK_TIME: "2000\nquorum.auth.enableSasl=true\nquorum.auth.learnerRequireSasl=true\nquorum.auth.serverRequireSasl=true\nquorum.auth.learner.loginContext=QuorumLearner\nquorum.auth.server.loginContext=QuorumServer"
      ZOOKEEPER_SERVERS: zookeeper1:22888:23888;zookeeper2:32888:33888;zookeeper3:42888:43888
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_jaas.conf
                  -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
                   -Dzookeeper.requireClientAuthScheme=sasl
    volumes:
      - $PWD/secrets:/etc/kafka/secrets
    ports:
      - "22181:22181"

  zookeeper2:
    image: confluentinc/cp-zookeeper:$TAG
    hostname: zookeeper2
    restart: on-failure:3
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: DEBUG
      ZOOKEEPER_TICK_TIME: "2000\nquorum.auth.enableSasl=true\nquorum.auth.learnerRequireSasl=true\nquorum.auth.serverRequireSasl=true\nquorum.auth.learner.loginContext=QuorumLearner\nquorum.auth.server.loginContext=QuorumServer"
      ZOOKEEPER_SERVERS: zookeeper1:22888:23888;zookeeper2:32888:33888;zookeeper3:42888:43888
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_jaas.conf
                  -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
                  -Dzookeeper.requireClientAuthScheme=sasl
    volumes:
      - $PWD/secrets:/etc/kafka/secrets
    ports:
      - "32181:32181"

  zookeeper3:
    image: confluentinc/cp-zookeeper:$TAG
    hostname: zookeeper3
    restart: on-failure:3
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: DEBUG
      ZOOKEEPER_TICK_TIME: "2000\nquorum.auth.enableSasl=true\nquorum.auth.learnerRequireSasl=true\nquorum.auth.serverRequireSasl=true\nquorum.auth.learner.loginContext=QuorumLearner\nquorum.auth.server.loginContext=QuorumServer"
      ZOOKEEPER_SERVERS: zookeeper1:22888:23888;zookeeper2:32888:33888;zookeeper3:42888:43888
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_jaas.conf
                  -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
                  -Dzookeeper.requireClientAuthScheme=sasl
    volumes:
      - $PWD/secrets:/etc/kafka/secrets
    ports:
      - "42181:42181"

  kafka1:
    image: confluentinc/cp-enterprise-kafka:$TAG
    hostname: kafka1
    container_name: kafka1
    restart: always
    ports:
      - "19092:19092"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    volumes:
      - $PWD/secrets:/etc/kafka/secrets
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:22181,zookeeper2:32181,zookeeper3:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:19092
      KAFKA_LOG4J_ROOT_LOGLEVEL: DEBUG
      KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka1:19092"
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/kafka_jaas.conf

  kafka2:
    image: confluentinc/cp-enterprise-kafka:$TAG
    hostname: kafk2
    container_name: kafka2
    restart: always
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    volumes:
      - $PWD/secrets:/etc/kafka/secrets
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:22181,zookeeper2:32181,zookeeper3:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29092
      KAFKA_LOG4J_ROOT_LOGLEVEL: DEBUG
      KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka2:29092"
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/kafka_jaas.conf

  kafka3:
    image: confluentinc/cp-enterprise-kafka:$TAG
    hostname: kafk3
    container_name: kafka3
    restart: always
    ports:
      - "39092:39092"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    volumes:
      - $PWD/secrets:/etc/kafka/secrets
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:22181,zookeeper2:32181,zookeeper3:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:39092
      KAFKA_LOG4J_ROOT_LOGLEVEL: DEBUG
      KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka3:39092"
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/kafka_jaas.conf
      

