version: '3.4'
services:
  zookeeper:
    build: ./zookeeper
    image: onprem/zookeeper:5.3.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
      
  kafka:
    build: ./kafka
    image: onprem/kafka:5.3.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    volumes:
      - $PWD/secrets:/secrets
    ports:
      - "9092:9092"
  
