version: '3.4'
services:
  zookeeper:
    build: ./zookeeper
    image: onprem/zookeeper:5.3.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
      
  kafka:
    build: ./kafka
    image: onprem/kafka:5.3.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    volumes:
      - $PWD/secrets:/secrets
    ports:
      - "9092:9092"
  
  connect:
    build: ./connect
    image: onprem/connect:5.3.0
    hostname: connect
    container_name: connect
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    volumes:
      - $PWD/secrets:/secrets
    environment:
      CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-5.2.1.jar

  schema-registry:
    build: ./schema-registry
    image: onprem/schema-registry:5.3.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - $PWD/secrets:/secrets
    ports:
      - "8081:8081"
  
  ksql-server:
    build: ./ksql-server
    image: onprem/ksql-server:5.3.0
    hostname: ksql-server
    container_name: ksql-server
    depends_on:
      - kafka
    ports:
      - "8088:8088"
    volumes:
      - $PWD/scripts:/scripts
      - $PWD/secrets:/secrets

  control-center:
    build: ./control-center
    image: onprem/control-center:5.3.0
    hostname: control-center
    container_name: control-center
    depends_on:
      - kafka
      - ksql-server
      - connect
    ports:
      - "9022:9022"
    volumes:
      - $PWD/secrets:/secrets
    environment:
      CONTROL_CENTER_OPTS: "-Djavax.net.ssl.trustStore=/secrets/control-center.truststore.jks \
      -Djavax.net.ssl.trustStorePassword=confluent \
      -Djavax.net.ssl.keyStore=/secrets/control-center.keystore.jks \
      -Djavax.net.ssl.keyStorePassword=confluent"
